version: '3'
services:
  my_node_container:
    image: node:latest
    container_name: my_node_container
    volumes:
      - ./app1:/app # Mapowanie katalogu app1 do katalogu /app w kontenerze
    command: sh -c "cd /app && npm install && npm start"
